### PR TITLE
improve typescript declaration files

### LINKED ISSUE #60: Could not find a declaration file for module 'connected-react-router/immutable'
After I started to use typescript, can I at least ignore it somehow ?

### PR DESCRIPTION
**Pull request by thomschke**
fix #60

### CODE REVIEW

**Comment by thomschke** [comment]
I have to bump `@types/react` from v15 to v16 due to breaking changes.

When using node_modules depending on @types/react with mixed major versions then you get compile errors like DefinitelyTyped/DefinitelyTyped#21242.

**Comment by supasate** [comment]
Hi @thomschke, is the file exactly the same with index.d.ts? I'm a typescript n00b and curious that can we reuse or reference to that existing file? So, we don't to maintain two files with have the same code.

**Comment by thomschke** [comment]
Hi @supasate, DRY version is up.

**Comment by supasate** [comment]
I revert this because it may affect people who use React 15.x. I'll merge this when we have a major upgrade.

**Comment by thomschke** [comment]
I understand. 

A lot of other projects define a wildcard version (`@types/react: "*"`) to prevent this compile problems.

**Comment by supasate** [comment]
@thomschke you can submit a new PR by using the wildcard if it helps.

**Pull request merged**
