### PR TITLE
Add query type definition for RouterState.location #381

### PR DESCRIPTION
**Pull request by TomIsion**
Find same question as #381 

`index.d.ts` file miss type definition for query in RouterState.location.

### CODE REVIEW

**Comment by supasate** [comment]
Thanks @TomIsion !

**Comment by webistomin** [comment]
Release it, please. 

Thanks!😊

**Comment by NGuldager** [comment]
+1 For a release please 😄

**Comment by myagkou** [comment]
Please release this.

**Comment by Hmoulvad** [comment]
Can we have this released please?

**Comment by supasate** [comment]
Released in v6.9.0. Sorry for a really long delay!

**Pull request merged**
