### PR TITLE
Also allow ^5.0.0 react-redux peer dependency

### PR DESCRIPTION
**Pull request by pete-otaqui**
the latest stable version of react-redux is 5.0.2, which seems to work fine with this library to me.

### CODE REVIEW

**Comment by supasate** [comment]
LGTM. Thanks for your contribution!

**Comment by pete-otaqui** [comment]
Great!

Any chance you could publish this to npm?

**Comment by supasate** [comment]
@pete-otaqui Done. Please check it out :) https://github.com/supasate/connected-react-router/releases

**Comment by olegstepura** [comment]
npm served `v2.0.0-alpha.3` without `lib` folder for me

**Comment by supasate** [comment]
Oh, sorry. I forgot to build the lib folder. Please wait.

**Comment by supasate** [comment]
@olegstepura Should be fixed now in `v2.0.0-alpha.4`.

**Comment by olegstepura** [comment]
@supasate Yep, it's fixed

**Pull request merged**
