### PR TITLE
Update react peer dependency to include v17

### PR DESCRIPTION
**Pull request by marekventur**
As far as I can tell it's working without a problem

### CODE REVIEW

**Comment by alexasselin008** [comment]
@supasate Could you take a look at this PR? The react version of connected-react-router is not up to date.

Thank you

**Review by ekacahya21 — APPROVED** [review]
LGTM

**Review by devinivy — APPROVED** [review]
Looks good over here too 👍

**Comment by aelawson** [comment]
@supasate Can we merge this? Would be nice to be able to use this library with React 17

**Comment by supasate** [comment]
LGTM. Thanks for your contribution @marekventur!

And sorry for keeping you all waiting. I'll release it soon!

**Comment by supasate** [comment]
Released in v6.9.0.

**Pull request merged**
