### PR TITLE
Implement: Windows development capability

### PR DESCRIPTION
**Pull request by KorobkaVadim**

### CODE REVIEW

**Comment by KorobkaVadim** [comment]
This change allows you to develop this library on a PC running Windows OS. But it breaks support for NodeJS v6 in development mode.

**Comment by supasate** [comment]
It's ok to drop node v6 support here as it's end of its LTS support. So, can you change the travis file to drop v6 as well?

**Comment by KorobkaVadim** [comment]
Fixed

**Comment by supasate** [comment]
Thanks @KorobkaVadim !

**Pull request merged**
