### PR TITLE
fix(actions): :bug: fix send isFirstRendering to onLocationChanged ac…

### PR DESCRIPTION
**Pull request by AlexeyAbretov**
…tion

meta: issue #259

### CODE REVIEW

**Comment by NikhilVerma** [comment]
I agree with this fix, seems like we need to add a unit test to make sure it doesn't break

**Comment by supasate** [comment]
LGTM! Thanks for the fix!

**Comment by azangru** [comment]
@supasate Could you please publish the fix to npm? We've just discovered this bug and are very eager to get rid of it.

**Comment by supasate** [comment]
Released in v6.3.2 :)

**Pull request merged**
