### PR TITLE
Create selectors to retrieve search and hash

### PR DESCRIPTION
**Pull request by antgonzales**
We can currently get the location and this action, this change adds the ability to retrieve the current search and hash.

### CODE REVIEW

**Comment by supasate** [comment]
LGTM! 

@antgonzales, please rebase. There is a small change in a previous PR that made this lib tree-shakable.

**Comment by antgonzales** [comment]
@supasate crap, I forgot to add Typescript support for these selectors. Let me push that up as well as the rebase. Thanks for the feedback!

**Comment by antgonzales** [comment]
@Annatsu @supasate ready for another round of reviews, I added some Typescript support that was missing as well. We had to add these definitions to our local development. It will be nice to be able to get rid of them.

**Comment by supasate** [comment]
Please add to src/immutable.js and src/seamless-immutable.js too. (It needs to be separated for tree-shakable.)

**Comment by antgonzales** [comment]
@supasate sorry haven't had the time over the holidays. Go ahead and merge and I'll do a fast follow this weekend.

**Pull request merged**
