### PR TITLE
Make time travelling optional

### PR DESCRIPTION
**Pull request by nickwaelkens**
Hi,

in my specific case, I'm dispatching a `replace` action whenever no locale is set in the URL to go to a correct URL. E.g. `mysite.com` would be considered wrong because I want my URL to be `mysite.com/en-us` by default.

For some reason (because of the check for time travelling) the URL would always jump back to the previous one, the one without locale...

This PR adds an extra prop to `ConnectedRouter` to disable the time travelling. Default value is still true, so I believe this could be merged without any issues.

Usage:
```js
    <ConnectedRouter allowTimetravel={false}>
        ...
    </ConnectedRouter>
```

### CODE REVIEW

**Comment by supasate** [comment]
@nickwaelkens Thanks for sharing this info and PR. 

Could you share me your problematic gist or repo? I'd like to inspect for the root cause.

**Comment by nickwaelkens** [comment]
We opted for a different approach that fixes the problem in the end, but I will make a small example of what was going wrong this weekend! Thanks for your patience @supasate.

**Comment by supasate** [comment]
Don't worry. No rush. Just do it when you're comfortable ^^.

**Comment by supasate** [comment]
Hi @nickwaelkens. Is there any update on this issue? I'd be happy to see the root cause and what alternative way you used to solve it.

**Comment by nickwaelkens** [comment]
Hi @supasate, sorry for my extremely late reply.

Basically, we ended up handling the redirects/rewrites using our Express server so we have proper 302's and we can remove the logic from the front-end application. I have very little time to recreate the problem, but this is the gist of it...

Make a HOC and put it before the connected router which handles the rewriting of the URL [like I described here](https://gist.github.com/nickwaelkens/828a6577031dceab2cdd1682845c2d53). Then in your mounted component it would look something like this:

```js
      <Provider store={store}>
        <L10nProvider history={history} store={store}>
          <App history={history} /> // connected-react-router happens inside App
        </L10nProvider>
      </Provider>
````

And because I trigger a `replace` in the L10nProvider the router thinks I'm in time travel mode, which I'm not...?

**Pull request closed without merging**
