### PR TITLE
Expose router reducer

### LINKED ISSUE #133: [Performance]: Redux state is re-created on EVERY action
Due to the way router reducer is [implemented](https://github.com/supasate/connected-react-router/blob/master/src/reducer.js#L35) it changes the reference of the entire state on every action. 

This causes an unnecessary update (or rather re-calculation of `mapStateToProps`) in all connected components.
The whole idea feels a bit of an overkill just to get the initial router state from the real history object.

I would suggest to support an alternative way to connect router reducer (without wrapper function).
The idea is following:
1. Create router reducer bound to history object to support initial state (see code below)
2. Export new `routerReducer` as a named export to inject manually (same as `react-router-redux` does it)

```
export const createRouterReducer = (history) => {
    const initialRouterState = fromJS({
        location: history.location,
        action: history.action,
    })
    
    return (state = initialRouterState, action) => {
        if (type === LOCATION_CHANGE) {
            return merge(state, payload)
        }

        return state
    }
}

// reducers.js inside client app
import {createRouterReducer} from "connected-react-router";
import {createBrowserHistory} from "history";

const history = createBrowserHistory();
const routerReducer = createRouterReducer(history);

const rootReducer = combineReducers({
    ...clientReducers,
    router: routerReducer
});
```

This should also solve #104. I'm ready to send a PR if you like the idea @supasate.

### PR DESCRIPTION
**Pull request by sgal**
*I created this PR to follow up on #132 and #140. One is closed and other one is stale, so hopefully this one gets to be merged*

## What kind of change does this PR introduce?
Refactoring and bugfix.

## What is the motivation behind this change?
Align public API with `react-router-redux` and allow various integrations (redux-loop, rematch, etc.). As a consequence - fix for #133.

## Did you add tests for your changes?
Yes, existing tests are updated and new one for #133.

## Did you update the documentation?
Yes, both plain and immutable structure docs are update. All examples are also updated.

## Does your PR introduce a breaking change?
Yes, public API is changed so major release is needed for this.

Fixes #133 #104 #79 . Closes #140

### CODE REVIEW

**Comment by schnubor** [comment]
2 PRs for such an essential feature and still none of them is merged, meh.

**Comment by supasate** [comment]
This is a really great PR! Due to it will change the way we use this library, it'll be a major update. I'd like to make sure that I spend enough time to check it thoroughly (I'll try it this or next weekend). In the meantime, I'd like the community to help check it if it breaks anything you're using or not if you migrate to this one.

**Comment by sgal** [comment]
I've tested this this PR in our app (30+ routes, 10k+ modules) and it works as expected. Did you have time to test it @supasate?

**Comment by YUANLIN327** [comment]
@supasate , it's been more than two weeks since you mentioned about checking the update. Would you please merge it ASAP?

**Comment by Bartekus** [comment]
Seriously, what the hold up? This PR is also fundamental to having a proper state interface attached to the rootReducer/combineReducers function for Typescript without workarounds.

**Comment by Eomerx** [comment]
when dou you guys will merge this pull request and publish a new tag? There is no point to return new state every time an action is dispatched.

**Comment by sgal** [comment]
@Eomerx I’m wondering about the state myself. Seems like @supasate completely forgot about this repo. Which also brings a lot of questions regarding reliability of this package.

**Comment by supasate** [comment]
I'm going to check on it this weekend (finger crossed). I'm super busy last month. Sorry about that.

**Comment by supasate** [comment]
The logic looks solid and It works like a charm! I really appreciate your end-to-end contribution for the description, codebase, test, examples, and documentation. Thank you for your patience in my very slow response!

**Comment by supasate** [comment]
Released in v5.0.0!

**Pull request merged**
