### PR TITLE
Support for react-redux v7

### PR DESCRIPTION
**Pull request by quarties**
I know that it is a duplicate of #303, but it looks like the author of that PR is not currently available, so I decided to create my own.

With current dependenciec all test are passed :-)

### CODE REVIEW

**Comment by thisissami** [comment]
Thanks for doing this. :) 

I am curious: what is the process like for merging PRs into this project? As somebody who has only been tangentially involved with open source projects in the past - I know quite little about how different projects operate. I'd love to learn a bit about how the decision-making works for a project like this.

**Comment by quarties** [comment]
> Thanks for doing this. :)
> 
> I am curious: what is the process like for merging PRs into this project? As somebody who has only been tangentially involved with open source projects in the past - I know quite little about how different projects operate. I'd love to learn a bit about how the decision-making works for a project like this.

@thisissami TBH I don't know. I believe that this project is a personal project of @supasate. According to old, similar PRs (like: #273) it looks like this awesome guy is maintaining the repo by his own. And kudos to him!

Protip that I could give you - if you are ever curious how the contribution in open-source project works, check old PRs and `CONTRIBUTION.md` file if there is any :-)

**Comment by bboydflo** [comment]
Hey @quarties, awesome job! I think maybe it's a good idea to update the readme as well. currently it says that reac-redux@7 is not supported, which is exactly what this PR is about.

**Comment by janklimo** [comment]
Thank you for this @quarties. Just to confirm, is it safe to bump the version without further changes? I came across the following in the `react-redux` changelog:

>Any library that attempts to access the store instance out of legacy context will break, because we now put the store state into a `<Context.Provider>` instead. Examples of this include `connected-react-router` and `react-redux-subspace`.

Though that's from [v6.0](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0) so hopefully that's been resolved since then?

**Comment by quarties** [comment]
@bboydflo good point, I had updated the README.md file as well.

@janklimo I hope so too, I've tested my fork with upgraded `react-redux` dependencies with my apps that use `connected-react-router` and everything worked fine. Also, the tests pass :-)

I believe if there is anything else that we would need to check, @supasate will point it.

**Comment by micburks** [comment]
Tested and working! LGTM!

**Comment by supasate** [comment]
Thanks @quarties for working on this and thanks everyone for helping test it.

I'm just relocated to another country and messing up with documents, banking, home hunting, new workplace, etc. So, let me merge and release this over the weekend.

**Comment by quarties** [comment]
@supasate take your time, you are doing great work anyway! Good luck with post-relocation issues <3

**Comment by robert-skarzycki** [comment]
Hi, @quarties - when this is going to be merged and new version released?

**Comment by quarties** [comment]
@supasate any news on this?

**Comment by supasate** [comment]
Released with v6.5.0.

**Pull request merged**
